grpc:
  port: 44044
  timeout: 15s
  jwtSecretKey: secretKey
  jwtTimeOut: 1h

logger:
  level: debug

postgres:
  host: localhost
  port: 5432
  db_name: users
  user: app_user
  password: app_user_pass
  sslmode: disable